api_project=Training00
apigateway_url=http://10.253.249.14:5555
apigateway_urls=http://10.253.14.73:5555,http://10.253.14.74:5555,http://10.253.249.14:5555,http://10.253.249.14:5555
apigateway_username=Administrator
apigateway_password=manage



# Git identity (UNTUK JENKINS)
git_user_name=Jenkins CI test
git_user_email=jenkins@local-apigw
